### PR TITLE
Up to Code Standards

### PR DESCRIPTION
**Pull request by AvarianKnight**
Bring advance duplicatior 2 up to the coding style guidelines. Also changes depredecated items like GetConVarNumber or GetConVarString to GetConVar(""):GetType()

### CODE REVIEW

**Comment by thegrb93** [comment]
@AvarianKnight you should open the pull request on https://github.com/wiremod/advdupe2

**Comment by thegrb93** [comment]
@AvarianKnight

**Comment by AvarianKnight** [comment]
Sorry @thegrb93 haven't checked my github, I'll make sure to do this when I finish testing to make sure this didn't break anything.

**Comment by thegrb93** [comment]
KK, sounds good

**Pull request closed without merging**
